name: Deploy Azure Function App

on:
  push:
    branches:
      - main   # Runs whenever code is pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Function App
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
