name: Deploy Function App and Update APIM
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Authenticate with Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Function App
    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: '.'

    # Import API into APIM using local OpenAPI file
    - name: Import API into APIM
      run: |
        echo "Importing API into APIM from local file..."

        # Check if API already exists
        existing_api=$(az apim api show \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --service-name ${{ secrets.AZURE_APIM_NAME }} \
          --api-id oms-export-api \
          --query "name" -o tsv 2>/dev/null || echo "")

        if [ ! -z "$existing_api" ]; then
          echo "API already exists, deleting it first..."
          az apim api delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --service-name ${{ secrets.AZURE_APIM_NAME }} \
            --api-id oms-export-api \
            --delete-revisions true \
            --yes
          echo "Existing API deleted"
        fi

        # Import the new API from repo's local file
        az apim api import \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --service-name ${{ secrets.AZURE_APIM_NAME }} \
          --path oms-export-api \
          --api-id oms-export-api \
          --display-name "OMS Export Analysis API" \
          --specification-format OpenApi \
          --specification-path deploy/openapi.json

        echo "API imported successfully into APIM"
